#!/usr/bin/env bash
# Generated by omacosy-theme-import.
export BAR_COLOR=0xe60a192f
export BAR_BG_SOLID=0xff0a192f
export ITEM_BG=0xff1c3a5e
export ACCENT=0xffe6b422
export LABEL_COLOR=0xfff2e2a4
export ICON_COLOR=0xfff2e2a4
export MUTED=0xff2c4668
export RED=0xffd9822b
export GREEN=0xff7fb3d5
export YELLOW=0xfff2e2a4
